import type { CaseData } from '../types';

export const CASE_001_DATA: CaseData = {
  id: 'case-001',
  caseNumber: '001',
  title: 'Case 001: The Missing Girl',
  tagline: 'Every phone has a story.',
  difficulty: 'Beginner',
  estimatedTime: '30 mins',
  victimName: 'Sarah Mehta',
  victimAge: 22,
  victimPhone: '+1 (555) 019-3817',
  briefing: {
    synopsis: 'On the morning of September 9th, 22-year-old Sarah Mehta failed to report to work and did not return to her apartment. Her personal NOVA smartphone was recovered near a northern roadside overlook.',
    initialStatus: 'Active Missing Person Investigation',
    directives: [
      'Examine Sarah\'s recovered smartphone to reconstruct her movements.',
      'Log extracted messages, calls, and location pings to the Investigation Board.',
      'Connect contradicting clues to formulate deductions regarding 3:17 AM.',
    ],
  },
  characters: [
    {
      id: 'sarah',
      name: 'Sarah Mehta',
      age: 22,
      role: 'Missing Person',
      personality: 'Warm, observant, intelligent and quietly self-possessed.',
      avatar: '/assets/case001/characters/sarah_profile.webp',
      phone: '+1 (555) 019-3817',
      relationship: 'Victim',
      bio: 'Junior Data Analyst at Ardent Corp. Last confirmed digital activity at 03:17 AM. Her personal smartphone was recovered in the field.',
      isSuspect: false,
      statusTag: 'MISSING',
    },
    {
      id: 'alex',
      name: 'Alex',
      age: 24,
      role: 'Ex-Boyfriend',
      personality: 'Charming and approachable with guarded confidence; emotionally complicated.',
      avatar: '/assets/case001/characters/alex_profile.webp',
      phone: '+1 (555) 014-8821',
      relationship: 'Ex-Boyfriend / Acquaintance',
      bio: 'Ex-boyfriend of Sarah. Sent text messages claiming he was asleep at home at 02:38 AM.',
      isSuspect: true,
      statusTag: 'PERSON OF INTEREST',
    },
    {
      id: 'maya',
      name: 'Maya',
      age: 22,
      role: 'Best Friend',
      personality: 'Expressive, outgoing, loyal and emotionally readable.',
      avatar: '/assets/case001/characters/maya_profile.webp',
      phone: '+1 (555) 018-4902',
      relationship: 'Best Friend & Confidante',
      bio: 'Sarah\'s closest confidante. Received a 02:32 AM warning message from Sarah instructing her to stay away from Central Station.',
      isSuspect: true,
      statusTag: 'PERSON OF INTEREST',
    },
    {
      id: 'ryan',
      name: 'Ryan',
      age: 25,
      role: 'Colleague',
      personality: 'Analytical, ambitious, reserved and professional.',
      avatar: '/assets/case001/characters/ryan_profile.webp',
      phone: '+1 (555) 012-7733',
      relationship: 'Work Colleague at Ardent Corp',
      bio: 'Works on the systems infrastructure team at Ardent Corp. Sent messages inquiring about server encryption keys.',
      isSuspect: true,
      statusTag: 'PERSON OF INTEREST',
    },
    {
      id: 'daniel',
      name: 'Daniel',
      age: 27,
      role: 'Private Contact',
      personality: 'Composed, confident and difficult to read.',
      avatar: '/assets/case001/characters/daniel_profile.webp',
      phone: '+1 (555) 017-6644',
      relationship: 'Transport Contact',
      bio: 'Contacted by Sarah earlier that evening to coordinate a pickup near the Riverside district.',
      isSuspect: true,
      statusTag: 'PERSON OF INTEREST',
    },
    {
      id: 'unknown',
      name: 'Unknown Caller',
      age: 0,
      role: 'Unknown Number',
      personality: 'Unidentified caller.',
      avatar: '/assets/case001/characters/unknown_avatar.webp',
      phone: '+1 (555) 000-3170',
      relationship: 'Unregistered Caller',
      bio: 'Unregistered caller connected to Sarah\'s phone for 42 seconds at 03:17 AM.',
      isSuspect: true,
      statusTag: 'UNKNOWN CALLER',
    },
  ],
  messages: [
    {
      id: 'thread-alex',
      participantId: 'alex',
      unreadCount: 0,
      pinned: true,
      messages: [
        {
          id: 'msg-alex-1',
          senderId: 'alex',
          text: 'Sarah, why did you pull those audit folders from the server room today?',
          timestamp: '11:15 PM',
          status: 'read',
        },
        {
          id: 'msg-alex-2',
          senderId: 'sarah',
          text: "Don't worry about it Alex. It's none of your business.",
          timestamp: '11:22 PM',
          status: 'read',
        },
        {
          id: 'msg-alex-3',
          senderId: 'alex',
          text: 'You have no idea who you are dealing with. Put it back before management notices.',
          timestamp: '11:28 PM',
          status: 'read',
        },
        {
          id: 'msg-alex-4',
          senderId: 'alex',
          text: 'Are you at your apartment? I am coming over right now.',
          timestamp: '02:05 AM',
          status: 'read',
        },
        {
          id: 'msg-alex-5',
          senderId: 'sarah',
          text: "Do NOT come here. I'm not home anyway. Stay away from me.",
          timestamp: '02:12 AM',
          status: 'read',
        },
        {
          id: 'msg-alex-6',
          senderId: 'alex',
          text: "Fine. Whatever. I'm exhausted and going to bed. I'm home all night.",
          timestamp: '02:38 AM',
          status: 'read',
          clueEvidenceId: 'EVD_MSG_ALEX_HOME',
          clueTooltip: 'Alex claims he is at home going to sleep at 02:38 AM.',
        },
        {
          id: 'msg-alex-7',
          senderId: 'alex',
          text: 'Sarah pick up your phone. Where did you go?!',
          timestamp: '03:10 AM',
          status: 'delivered',
        },
      ],
    },
    {
      id: 'thread-maya',
      participantId: 'maya',
      unreadCount: 0,
      pinned: true,
      messages: [
        {
          id: 'msg-maya-1',
          senderId: 'maya',
          text: 'Hey babe, movie night this Friday? You seemed super stressed all week!',
          timestamp: '08:45 PM',
          status: 'read',
        },
        {
          id: 'msg-maya-2',
          senderId: 'sarah',
          text: 'I really hope I can make it Maya... things got really complicated at work.',
          timestamp: '09:10 PM',
          status: 'read',
        },
        {
          id: 'msg-maya-3',
          senderId: 'maya',
          text: 'Did Alex do something again? Tell me!',
          timestamp: '09:12 PM',
          status: 'read',
        },
        {
          id: 'msg-maya-4',
          senderId: 'sarah',
          text: 'Maya, listen to me carefully. If anyone asks where I went tonight, you know nothing. Do NOT go near Central Station.',
          timestamp: '02:32 AM',
          status: 'read',
          clueEvidenceId: 'EVD_MSG_MAYA_WARNING',
          clueTooltip: 'Sarah warns Maya to stay away from Central Station at 02:32 AM.',
        },
        {
          id: 'msg-maya-5',
          senderId: 'maya',
          text: 'Sarah you are terrifying me!! Please answer my call! Where are you going?!',
          timestamp: '02:34 AM',
          status: 'read',
        },
        {
          id: 'msg-maya-6',
          senderId: 'maya',
          text: 'I just called you. Please tell me you are safe.',
          timestamp: '03:02 AM',
          status: 'delivered',
        },
      ],
    },
    {
      id: 'thread-ryan',
      participantId: 'ryan',
      unreadCount: 0,
      messages: [
        {
          id: 'msg-ryan-1',
          senderId: 'ryan',
          text: 'Sarah, the encryption keys for the Vanguard project archive were moved from the staging server.',
          timestamp: '10:45 PM',
          status: 'read',
        },
        {
          id: 'msg-ryan-2',
          senderId: 'sarah',
          text: 'I know. They are in safe hands now.',
          timestamp: '10:50 PM',
          status: 'read',
        },
        {
          id: 'msg-ryan-3',
          senderId: 'ryan',
          text: 'You have made a grave mistake. You will lose everything over this.',
          timestamp: '10:54 PM',
          status: 'read',
          clueEvidenceId: 'EVD_MSG_RYAN_THREAT',
          clueTooltip: 'Ryan messages Sarah regarding the Vanguard project archive keys.',
        },
        {
          id: 'msg-ryan-4',
          senderId: 'ryan',
          text: 'I hope you enjoyed your coffee at Bluebird.',
          timestamp: '02:44 AM',
          status: 'read',
        },
      ],
    },
    {
      id: 'thread-daniel',
      participantId: 'daniel',
      unreadCount: 0,
      messages: [
        {
          id: 'msg-daniel-1',
          senderId: 'sarah',
          text: 'I need private transport tonight. Cash only. No questions asked.',
          timestamp: '01:15 AM',
          status: 'read',
        },
        {
          id: 'msg-daniel-2',
          senderId: 'daniel',
          text: 'Understood. Where and what time?',
          timestamp: '01:18 AM',
          status: 'read',
        },
        {
          id: 'msg-daniel-3',
          senderId: 'sarah',
          text: 'Riverside Overlook. North entrance. 03:30 AM sharp.',
          timestamp: '01:22 AM',
          status: 'read',
          clueEvidenceId: 'EVD_MSG_DANIEL_RENDEZVOUS',
          clueTooltip: 'Sarah arranges emergency rendezvous at Riverside Overlook for 03:30 AM.',
        },
        {
          id: 'msg-daniel-4',
          senderId: 'daniel',
          text: 'I will be there in the black hatchback. If I see anyone following you, I drive away.',
          timestamp: '01:25 AM',
          status: 'read',
        },
      ],
    },
    {
      id: 'thread-unknown',
      participantId: 'unknown',
      unreadCount: 1,
      messages: [
        {
          id: 'msg-unk-1',
          senderId: 'unknown',
          text: 'We know what you took from Floor 14.',
          timestamp: '01:43 AM',
          status: 'read',
        },
        {
          id: 'msg-unk-2',
          senderId: 'unknown',
          text: 'Drop the drive at the station lockers before 03:15 or you will not see morning.',
          timestamp: '02:15 AM',
          status: 'read',
          clueEvidenceId: 'EVD_MSG_UNKNOWN_EXTORTION',
          clueTooltip: 'Extortion message demanding Sarah leave the drive at station lockers.',
        },
        {
          id: 'msg-unk-3',
          senderId: 'unknown',
          text: 'You have 2 minutes to answer your phone.',
          timestamp: '03:16 AM',
          status: 'delivered',
        },
      ],
    },
  ],
  photos: [
    {
      id: 'photo-1',
      title: 'Sarah Selfie at Home',
      thumbnail: '/assets/case001/gallery/sarah_selfie_home.webp',
      fullImage: '/assets/case001/gallery/sarah_selfie_home.webp',
      category: 'selfie',
      caption: 'Quiet evening at home.',
      exif: {
        capturedAt: 'Sep 7',
        time: '08:14 PM',
        location: "Sarah's Apartment",
        camera: 'NOVA 4X Pro',
      },
    },
    {
      id: 'photo-2',
      title: 'Coffee at Bluebird',
      thumbnail: '/assets/case001/gallery/sarah_selfie_cafe.webp',
      fullImage: '/assets/case001/gallery/sarah_selfie_cafe.webp',
      category: 'selfie',
      caption: 'Afternoon coffee break at Bluebird.',
      exif: {
        capturedAt: 'Sep 8',
        time: '03:20 PM',
        location: 'Bluebird Cafe, 4th Ave',
        camera: 'NOVA 4X Pro',
      },
    },
    {
      id: 'photo-3',
      title: 'Afternoon at Riverside',
      thumbnail: '/assets/case001/gallery/sarah_maya_day.webp',
      fullImage: '/assets/case001/gallery/sarah_maya_day.webp',
      category: 'daily',
      caption: 'Walk by the river promenade with Maya.',
      exif: {
        capturedAt: 'Sep 5',
        time: '05:40 PM',
        location: 'Riverside Promenade',
        camera: 'NOVA 4X Pro',
      },
    },
    {
      id: 'photo-4',
      title: 'Old Memories with Alex',
      thumbnail: '/assets/case001/gallery/sarah_alex_old.webp',
      fullImage: '/assets/case001/gallery/sarah_alex_old.webp',
      category: 'daily',
      caption: 'Rooftop gathering last summer.',
      exif: {
        capturedAt: 'Aug 14',
        time: '09:15 PM',
        location: 'Downtown Rooftop',
        camera: 'NOVA 4X Pro',
      },
    },
    {
      id: 'photo-5',
      title: 'Floor 14 Workstation',
      thumbnail: '/assets/case001/gallery/sarah_office.webp',
      fullImage: '/assets/case001/gallery/sarah_office.webp',
      category: 'daily',
      caption: 'Late shift at Tech Park.',
      exif: {
        capturedAt: 'Sep 8',
        time: '06:30 PM',
        location: 'Floor 14, Tech Park Tower',
        camera: 'NOVA 4X Pro',
      },
    },
    {
      id: 'photo-6',
      title: 'Bluebird Cafe Corner',
      thumbnail: '/assets/case001/gallery/coffee_table.webp',
      fullImage: '/assets/case001/gallery/coffee_table.webp',
      category: 'location',
      caption: 'Corner booth with espresso.',
      exif: {
        capturedAt: 'Sep 8',
        time: '03:25 PM',
        location: 'Bluebird Cafe',
        camera: 'NOVA 4X Pro',
      },
    },
    {
      id: 'photo-7',
      title: 'City at Dusk',
      thumbnail: '/assets/case001/gallery/city_evening.webp',
      fullImage: '/assets/case001/gallery/city_evening.webp',
      category: 'location',
      caption: 'Evening transit commute.',
      exif: {
        capturedAt: 'Sep 7',
        time: '07:10 PM',
        location: 'Central District',
        camera: 'NOVA 4X Pro',
      },
    },
    {
      id: 'photo-8',
      title: 'Notes & Reading',
      thumbnail: '/assets/case001/gallery/book_notes.webp',
      fullImage: '/assets/case001/gallery/book_notes.webp',
      category: 'daily',
      caption: 'Weekend study notes.',
      exif: {
        capturedAt: 'Sep 6',
        time: '02:00 PM',
        location: "Sarah's Apartment",
        camera: 'NOVA 4X Pro',
      },
    },
    {
      id: 'photo-9',
      title: 'Maya Selfie',
      thumbnail: '/assets/case001/gallery/maya_selfie.webp',
      fullImage: '/assets/case001/gallery/maya_selfie.webp',
      category: 'selfie',
      caption: 'Maya sent this from downtown.',
      exif: {
        capturedAt: 'Sep 8',
        time: '01:15 PM',
        location: 'Central Plaza',
        camera: 'NOVA 4X Pro',
      },
    },
    {
      id: 'photo-10',
      title: 'Tech Park Analyst Team',
      thumbnail: '/assets/case001/gallery/office_team.webp',
      fullImage: '/assets/case001/gallery/office_team.webp',
      category: 'daily',
      caption: 'Quarterly review team photo.',
      exif: {
        capturedAt: 'Sep 4',
        time: '11:00 AM',
        location: 'Ardent Tech Park Tower',
        camera: 'NOVA 4X Pro',
      },
    },
    // Clue Photographs in Gallery/Storage
    {
      id: 'photo-clue-1',
      title: 'Bluebird Cafe at Night',
      thumbnail: '/assets/case001/clues/bluebird_cafe_0241.webp',
      fullImage: '/assets/case001/clues/bluebird_cafe_0241.webp',
      category: 'suspicious',
      caption: 'Late night espresso outside Bluebird.',
      exif: {
        capturedAt: 'Sep 9',
        time: '02:41 AM',
        location: 'Bluebird Cafe, 4th Ave',
        coordinates: '40.7308, -73.9973',
        camera: 'NOVA 4X Pro',
      },
      clueEvidenceId: 'EVD_PHOTO_REFLECTION',
    },
    {
      id: 'photo-clue-2',
      title: 'Central Station Concourse (02:58 AM)',
      thumbnail: '/assets/case001/clues/central_station_0302.webp',
      fullImage: '/assets/case001/clues/central_station_0302.webp',
      category: 'suspicious',
      caption: 'Quiet concourse mezzanine.',
      exif: {
        capturedAt: 'Sep 9',
        time: '02:58 AM',
        location: 'Central Station Concourse',
        coordinates: '40.7505, -73.9934',
        camera: 'NOVA 4X Pro',
      },
      clueEvidenceId: 'EVD_PHOTO_EXIF_STATION',
    },
  ],
  calls: [
    {
      id: 'call-1',
      contactId: 'maya',
      phoneNumber: '+1 (555) 018-4902',
      type: 'missed',
      timestamp: '02:35 AM',
      duration: '0:00',
      hasAudioVoicemail: true,
      voicemailDuration: '0:18',
      voicemailTranscript: '"Sarah please! Pick up the phone! I saw Alex leaving his place in a hurry. What is happening?!"',
      clueEvidenceId: 'EVD_CALL_MAYA_230',
    },
    {
      id: 'call-2',
      contactId: 'alex',
      phoneNumber: '+1 (555) 014-8821',
      type: 'outgoing',
      timestamp: '02:10 AM',
      duration: '0:34',
    },
    {
      id: 'call-3',
      contactId: 'unknown',
      phoneNumber: '+1 (555) 000-3170',
      type: 'incoming',
      timestamp: '03:17 AM',
      duration: '0:42',
      clueEvidenceId: 'EVD_CALL_317',
    },
    {
      id: 'call-4',
      contactId: 'alex',
      phoneNumber: '+1 (555) 014-8821',
      type: 'missed',
      timestamp: '03:22 AM',
      duration: '0:00',
      hasAudioVoicemail: true,
      voicemailDuration: '0:22',
      voicemailTranscript: '"Sarah I am at Central Station right now! Where are you?! We need to talk before it\'s too late!"',
      clueEvidenceId: 'EVD_CALL_ALEX_VOICEMAIL',
    },
    {
      id: 'call-5',
      contactId: 'daniel',
      phoneNumber: '+1 (555) 017-6644',
      type: 'outgoing',
      timestamp: '03:23 AM',
      duration: '0:15',
    },
  ],
  locations: [
    {
      id: 'loc-apartment',
      name: "Sarah's Apartment",
      category: 'residence',
      coordinates: { x: 25, y: 35 },
      address: '242 East 28th Street, Apt 4B',
      description: 'Sarah departed her apartment abruptly on foot at 02:14 AM.',
      pings: [
        { time: '02:14 AM', trackedPerson: 'Sarah Mehta', details: 'Device departs residential WiFi.' },
      ],
    },
    {
      id: 'loc-bluebird',
      name: 'Bluebird Cafe',
      category: 'commercial',
      coordinates: { x: 42, y: 48 },
      address: '118 4th Avenue',
      description: 'Sarah stopped for 8 minutes. WiFi log and coffee receipt recorded.',
      pings: [
        { time: '02:41 AM', trackedPerson: 'Sarah Mehta', details: 'WiFi connection established.' },
      ],
    },
    {
      id: 'loc-station',
      name: 'Central Station (Locker Area)',
      category: 'transit',
      coordinates: { x: 62, y: 58 },
      address: '89 East 42nd Street, Lower Mezzanine',
      description: 'Locker 28 accessed at 03:17 AM. Cell towers also register Alex\'s phone at 02:47 AM.',
      pings: [
        { time: '02:47 AM', trackedPerson: 'Alex', details: 'Cell tower ping at 42nd St concourse.', clueEvidenceId: 'EVD_MAP_ALEX_STATION' },
        { time: '02:58 AM', trackedPerson: 'Sarah Mehta', details: 'Concourse photo captured.' },
        { time: '03:17 AM', trackedPerson: 'Sarah Mehta', details: '42-second call connection.' },
      ],
    },
    {
      id: 'loc-riverside',
      name: 'Riverside Overlook',
      category: 'danger',
      coordinates: { x: 84, y: 78 },
      address: 'Riverside Drive & 116th Pier',
      description: 'Final cellular telemetry ping received at 03:24 AM before device went dark.',
      pings: [
        { time: '03:24 AM', trackedPerson: 'Sarah Mehta', details: 'Final telemetry transmission.', clueEvidenceId: 'EVD_MAP_RIVERSIDE_PING' },
      ],
    },
  ],
  notes: [
    {
      id: 'note-1',
      title: 'Locker 28 / Protocol',
      date: 'Sep 8, 11:42 PM',
      content: 'Locker 28 code: 8-3-1-7\nLeave drive before 3:17 AM.\nDaniel pickup at Riverside Overlook (03:30 AM).\nIf anything happens, Maya has the backup decryptor.',
      clueEvidenceId: 'EVD_NOTE_LOCKER28',
    },
    {
      id: 'note-2',
      title: 'Project Vanguard Summary',
      date: 'Sep 8, 08:15 PM',
      content: 'Audit logs reveal systematic falsification of federal safety metrics across Q2 and Q3. Master ledger stored on external thumb drive.',
      clueEvidenceId: 'EVD_NOTE_VANGUARD',
    },
    {
      id: 'note-3',
      title: 'Grocery & Errands',
      date: 'Sep 7, 02:20 PM',
      content: '- Oat milk\n- Coffee beans\n- Return Maya\'s jacket\n- Dry cleaner ticket #4419',
    },
  ],
  browserHistory: [
    {
      id: 'hist-1',
      title: 'Central Station Luggage Lockers Operating Hours',
      url: 'https://station-lockers.transit.org/info',
      time: '11:35 PM',
    },
    {
      id: 'hist-2',
      title: 'Federal Whistleblower Protection Hotline',
      url: 'https://whistleblower.gov/reporting',
      time: '09:40 PM',
    },
    {
      id: 'hist-3',
      title: 'Emergency Disposable SIM Activation Guide',
      url: 'https://techguides.net/esim-burner',
      time: '01:05 AM',
    },
  ],
  files: [
    {
      id: 'file-1',
      name: 'vanguard_audit_q3_raw.xlsx',
      type: 'text',
      size: '4.2 MB',
      modified: 'Sep 8, 10:15 PM',
      contentPreview: 'Spreadsheet comparing internal environmental sensor telemetry vs altered regulatory filings.',
    },
    {
      id: 'file-2',
      name: 'station_locker_receipt_28.pdf',
      type: 'image',
      size: '280 KB',
      modified: 'Sep 8, 11:38 PM',
      contentPreview: 'Electronic reservation receipt for Locker #28 at Central Station concourse.',
    },
  ],
  evidenceList: [
    {
      id: 'EVD_MSG_ALEX_HOME',
      caseId: 'case-001',
      title: "Alex's Message (02:38 AM)",
      category: 'Message',
      importance: 'critical',
      sourceApp: 'Messages',
      timestamp: '02:38 AM',
      description: 'Alex claims: "I\'m exhausted and going to bed. I\'m home all night."',
      sourceDetail: 'Messages • Thread with Alex',
      tag: 'Alex Alibi',
    },
    {
      id: 'EVD_MAP_ALEX_STATION',
      caseId: 'case-001',
      title: "Alex's Cell Ping at Central Station",
      category: 'Location',
      importance: 'critical',
      sourceApp: 'Maps',
      timestamp: '02:47 AM',
      description: 'Cell tower records show Alex\'s device near Central Station at 02:47 AM, contradicting his message.',
      sourceDetail: 'Maps • Central Station Tower Logs',
      tag: 'Contradiction',
    },
    {
      id: 'EVD_MSG_MAYA_WARNING',
      caseId: 'case-001',
      title: "Sarah's Warning to Maya (02:32 AM)",
      category: 'Message',
      importance: 'supporting',
      sourceApp: 'Messages',
      timestamp: '02:32 AM',
      description: 'Sarah warns Maya: "If anyone asks where I went tonight, you know nothing. Do NOT go near Central Station."',
      sourceDetail: 'Messages • Thread with Maya',
      tag: 'Warning',
    },
    {
      id: 'EVD_CALL_MAYA_230',
      caseId: 'case-001',
      title: "Maya's Voicemail (02:35 AM)",
      category: 'Call',
      importance: 'supporting',
      sourceApp: 'Phone',
      timestamp: '02:35 AM',
      description: 'Maya leaves frantic voicemail: "I saw Alex leaving his place in a hurry. What is happening?!"',
      sourceDetail: 'Phone • Voicemail from Maya',
      tag: 'Voicemail',
    },
    {
      id: 'EVD_NOTE_LOCKER28',
      caseId: 'case-001',
      title: 'Locker 28 Access Note',
      category: 'Document',
      importance: 'critical',
      sourceApp: 'Notes',
      timestamp: '11:42 PM',
      description: 'Sarah\'s note: "Locker 28 code: 8-3-1-7. Leave drive before 3:17 AM. Daniel pickup at Riverside Overlook."',
      sourceDetail: 'Notes • Personal Vault',
      tag: 'Passcode',
    },
    {
      id: 'EVD_CALL_317',
      caseId: 'case-001',
      title: '3:17 AM Unknown Number Call',
      category: 'Call',
      importance: 'critical',
      sourceApp: 'Phone',
      timestamp: '03:17 AM',
      description: '42-second incoming call connected from Unknown Number (+1-555-000-3170) while Sarah was at Central Station.',
      sourceDetail: 'Phone • Call Logs',
      tag: '3:17 Connection',
    },
    {
      id: 'EVD_MSG_UNKNOWN_EXTORTION',
      caseId: 'case-001',
      title: 'Extortion Message from Unknown Number',
      category: 'Message',
      importance: 'critical',
      sourceApp: 'Messages',
      timestamp: '02:15 AM',
      description: 'Unknown number demands: "Drop the drive at the station lockers before 03:15 or you will not see morning."',
      sourceDetail: 'Messages • Thread with Unknown',
      tag: 'Threat',
    },
    {
      id: 'EVD_VOICE_MEMO_317',
      caseId: 'case-001',
      title: 'Emergency Voice Memo (03:20 AM)',
      category: 'Document',
      importance: 'critical',
      sourceApp: 'VoiceMemos',
      timestamp: '03:20 AM',
      description: 'Sarah reports a black sedan tailing her from Central Station toward Riverside; confirms drive is in Locker 28.',
      sourceDetail: 'Voice Memos • Audio Recording',
      tag: 'Pursuit',
    },
    {
      id: 'EVD_MAP_RIVERSIDE_PING',
      caseId: 'case-001',
      title: 'Final GPS Ping at Riverside (03:24 AM)',
      category: 'Location',
      importance: 'critical',
      sourceApp: 'Maps',
      timestamp: '03:24 AM',
      description: 'Sarah\'s device transmitted its final cellular signal at Riverside Overlook before going dark.',
      sourceDetail: 'Maps • Telemetry Ping',
      tag: 'Final Signal',
    },
    {
      id: 'EVD_PHOTO_EXIF_STATION',
      caseId: 'case-001',
      title: 'Central Station Concourse Photo EXIF',
      category: 'Photo',
      importance: 'supporting',
      sourceApp: 'Photos',
      timestamp: '02:58 AM',
      description: 'Photo EXIF confirms Sarah was inside Central Station concourse at 02:58 AM.',
      sourceDetail: 'Photos • EXIF Metadata',
      tag: 'Photo Log',
    },
    {
      id: 'EVD_PHOTO_REFLECTION',
      caseId: 'case-001',
      title: 'Bluebird Cafe Photo EXIF',
      category: 'Photo',
      importance: 'supporting',
      sourceApp: 'Photos',
      timestamp: '02:41 AM',
      description: 'Photo metadata confirms Sarah was at Bluebird Cafe at 02:41 AM.',
      sourceDetail: 'Photos • EXIF Metadata',
      tag: 'Photo Log',
    },
    {
      id: 'EVD_MSG_RYAN_THREAT',
      caseId: 'case-001',
      title: "Ryan's Message Regarding Keys",
      category: 'Message',
      importance: 'supporting',
      sourceApp: 'Messages',
      timestamp: '10:54 PM',
      description: 'Ryan messages Sarah: "The encryption keys for Vanguard were moved... You have made a grave mistake."',
      sourceDetail: 'Messages • Thread with Ryan',
      tag: 'Threat',
    },
    {
      id: 'EVD_MSG_DANIEL_RENDEZVOUS',
      caseId: 'case-001',
      title: 'Rendezvous Plan with Daniel',
      category: 'Message',
      importance: 'supporting',
      sourceApp: 'Messages',
      timestamp: '01:22 AM',
      description: 'Sarah arranged emergency transport at Riverside Overlook North entrance for 03:30 AM.',
      sourceDetail: 'Messages • Thread with Daniel',
      tag: 'Escape',
    },
    {
      id: 'EVD_CALL_ALEX_VOICEMAIL',
      caseId: 'case-001',
      title: "Alex's Voicemail at Central Station",
      category: 'Call',
      importance: 'supporting',
      sourceApp: 'Phone',
      timestamp: '03:22 AM',
      description: 'Alex leaves voicemail at 03:22 AM: "Sarah I am at Central Station right now! Where are you?!"',
      sourceDetail: 'Phone • Voicemail from Alex',
      tag: 'Voicemail',
    },
  ],
  deductions: [
    {
      id: 'DED_ALEX_ALIBI',
      title: "Alex's Alibi is False",
      contradictionType: "Alibi Inconsistency",
      unlockedQuestion: 'Why was Alex near Central Station after claiming he was home?',
      insight: 'Alex claimed he was at home going to sleep at 02:38 AM, but cell tower records place his device near Central Station at 02:47 AM.',
      impactScore: 300,
      requiredEvidenceIds: ['EVD_MSG_ALEX_HOME', 'EVD_MAP_ALEX_STATION'],
    },
    {
      id: 'DED_LOCKER_OPERATION',
      title: 'The Locker 28 Plan',
      contradictionType: 'Whistleblower Protocol',
      unlockedQuestion: 'Did Sarah manage to access Locker 28 before being interrupted?',
      insight: 'Sarah planned to deposit the master archive into Locker 28 at Central Station with passcode 8-3-1-7 before departing.',
      impactScore: 350,
      requiredEvidenceIds: ['EVD_NOTE_LOCKER28', 'EVD_PHOTO_EXIF_STATION'],
    },
    {
      id: 'DED_THE_BLACKMAIL_THREAT',
      title: 'The 3:17 Threat Call',
      contradictionType: 'Extortion Sequence',
      unlockedQuestion: 'Who is the unknown caller and how did they track her movements?',
      insight: 'An unknown caller connected to Sarah\'s phone for 42 seconds at 3:17 AM while she was at Central Station, demanding the drive.',
      impactScore: 400,
      requiredEvidenceIds: ['EVD_CALL_317', 'EVD_MSG_UNKNOWN_EXTORTION'],
    },
    {
      id: 'DED_THE_RIVERSIDE_PURSUIT',
      title: 'The Riverside Interception',
      contradictionType: 'Physical Interception',
      unlockedQuestion: 'What happened to Sarah when her signal stopped at Riverside Overlook?',
      insight: 'Sarah fled Central Station toward Riverside Overlook to meet Daniel\'s vehicle, pursued by an unknown vehicle until her signal ceased at 03:24 AM.',
      impactScore: 450,
      requiredEvidenceIds: ['EVD_VOICE_MEMO_317', 'EVD_MAP_RIVERSIDE_PING'],
    },
  ],
  timeline: [
    {
      id: 'time-1130',
      time: '11:30 PM',
      order: 1,
      title: 'Phone Leaves Tech Park Area',
      description: 'Device network logs record Sarah leaving Ardent Corp Tech Park.',
      source: 'Network / Location Record',
      isLockedByDefault: false,
    },
    {
      id: 'time-0143',
      time: '01:43 AM',
      order: 2,
      title: 'First Message from Unknown Number',
      description: 'Incoming text message received from unregistered number referencing Floor 14.',
      source: 'Messages Log',
      isLockedByDefault: false,
    },
    {
      id: 'time-0214',
      time: '02:14 AM',
      order: 3,
      title: 'Sarah Departs Apartment',
      description: 'Cellular location indicates movement away from 28th Street.',
      source: 'Location History',
      isLockedByDefault: false,
    },
    {
      id: 'time-0232',
      time: '02:32 AM',
      order: 4,
      title: 'Warning Message to Maya',
      description: 'Sarah texts Maya advising her to avoid Central Station.',
      source: 'Messages Log',
      isLockedByDefault: true,
      unlockedByEvidenceId: 'EVD_MSG_MAYA_WARNING',
    },
    {
      id: 'time-0235',
      time: '02:35 AM',
      order: 5,
      title: "Maya's Voicemail",
      description: 'Maya reports seeing Alex leave his residence in haste.',
      source: 'Voicemail Record',
      isLockedByDefault: true,
      unlockedByEvidenceId: 'EVD_CALL_MAYA_230',
    },
    {
      id: 'time-0241',
      time: '02:41 AM',
      order: 6,
      title: 'Activity at Bluebird Cafe',
      description: 'Device logs into Bluebird Cafe network on 4th Avenue.',
      source: 'Photo & Network Metadata',
      isLockedByDefault: true,
      unlockedByEvidenceId: 'EVD_PHOTO_REFLECTION',
    },
    {
      id: 'time-0247',
      time: '02:47 AM',
      order: 7,
      title: 'Alex Device Near Central Station',
      description: 'Cell tower records locate Alex\'s device near Central Station.',
      source: 'Cell Tower Pings',
      isLockedByDefault: true,
      unlockedByEvidenceId: 'EVD_MAP_ALEX_STATION',
    },
    {
      id: 'time-0258',
      time: '02:58 AM',
      order: 8,
      title: 'Concourse Entry at Central Station',
      description: 'Photo and concourse records confirm presence at Central Station.',
      source: 'Photo Metadata & Network Log',
      isLockedByDefault: true,
      unlockedByEvidenceId: 'EVD_PHOTO_EXIF_STATION',
    },
    {
      id: 'time-0317',
      time: '03:17 AM',
      order: 9,
      title: '03:17 AM — The Unknown Call',
      description: 'Unregistered incoming call connected for 42 seconds at Central Station.',
      source: 'Call Record & Cell Trace',
      isKey317Event: true,
      isLockedByDefault: true,
      unlockedByEvidenceId: 'EVD_CALL_317',
    },
    {
      id: 'time-0320',
      time: '03:20 AM',
      order: 10,
      title: 'Emergency Audio Memo Recorded',
      description: 'Audio recording created describing vehicular pursuit from the station.',
      source: 'Voice Memo 0320',
      isLockedByDefault: true,
      unlockedByEvidenceId: 'EVD_VOICE_MEMO_317',
    },
    {
      id: 'time-0324',
      time: '03:24 AM',
      order: 11,
      title: 'Final Cellular Transmission at Riverside Overlook',
      description: 'Sarah\'s device transmits final location telemetry before going dark.',
      source: 'Maps Final GPS Ping',
      isLockedByDefault: true,
      unlockedByEvidenceId: 'EVD_MAP_RIVERSIDE_PING',
    },
  ],
  hints: [
    {
      id: 'hint-1',
      tier: 1,
      costPoints: 100,
      title: 'Check the timestamps in Messages',
      text: 'Compare conversation timestamps between Alex\'s messages around 02:38 AM and location records.',
    },
    {
      id: 'hint-2',
      tier: 2,
      costPoints: 250,
      title: 'Compare Alex\'s alibi with cell logs',
      text: 'Alex stated he was home sleeping at 02:38 AM. What does the Central Station cell ping show at 02:47 AM?',
    },
    {
      id: 'hint-3',
      tier: 3,
      costPoints: 500,
      title: 'Investigate the 3:17 AM connection',
      text: 'Connect the 3:17 AM call record with the extortion messages to understand what happened at the station.',
    },
  ],
  solution: {
    correctSuspectId: 'unknown',
    correctLocationId: 'loc-riverside',
    correctCriticalTime: '03:17 AM',
    correctKeyActionMotive: 'corporate_interception',
    mandatoryEvidenceIds: [
      'EVD_MSG_ALEX_HOME',
      'EVD_MAP_ALEX_STATION',
      'EVD_NOTE_LOCKER28',
      'EVD_CALL_317',
      'EVD_VOICE_MEMO_317',
      'EVD_MAP_RIVERSIDE_PING',
    ],
    mandatoryDeductionIds: [
      'DED_ALEX_ALIBI',
      'DED_LOCKER_OPERATION',
      'DED_THE_BLACKMAIL_THREAT',
      'DED_THE_RIVERSIDE_PURSUIT',
    ],
  },
  endings: {
    true_ending: {
      id: 'true_ending',
      type: 'solved',
      title: 'CASE SOLVED — THE TRUTH OF 3:17',
      subtitle: 'Official Investigative Verdict',
      narrative: [
        'You successfully reconstructed the sequence of events of September 9th.',
        'Sarah Mehta extracted critical evidence of corporate misconduct from Floor 14 at Ardent Corp, safeguarding the files in Locker 28 at Central Station with passcode 8-3-1-7.',
        'Alex lied about being asleep at home and rushed to Central Station to urge Sarah to back down—creating an inconsistent alibi that initially drew suspicion.',
        'However, an unknown operative tracked Sarah to Central Station. At 3:17 AM, during the locker deposit, the operative placed an extortion call.',
        'Sarah fled the station toward the Riverside Overlook rendezvous point. At 03:24 AM, her vehicle was intercepted and her phone was left behind at the scene.',
        'With your conclusive evidence report, law enforcement retrieved the master drive from Locker 28, secured search warrants, and located Sarah safely.',
      ],
      scoreMultiplier: 1.5,
      rank: 'S',
    },
    wrong_suspect_alex: {
      id: 'wrong_suspect_alex',
      type: 'failed',
      title: 'THEORY FLAWED — ALEX WAS NOT THE INTERCEPTOR',
      subtitle: 'Incomplete Theory',
      narrative: [
        'You accused Alex based on his false alibi at Central Station.',
        'While Alex did lie about being asleep, concourse cameras confirm he arrived after Sarah had already departed.',
        'Alex wanted Sarah to return the files to protect his own position, but he did not carry out the interception at Riverside Overlook.',
      ],
      rebuttalPoints: [
        'Sarah\'s 03:20 AM emergency memo specifically referenced a tailing surveillance sedan.',
        'Alex was still at Central Station at 03:22 AM leaving a frantic voicemail.',
      ],
      scoreMultiplier: 0.4,
      rank: 'F',
    },
    wrong_suspect_ryan: {
      id: 'wrong_suspect_ryan',
      type: 'failed',
      title: 'THEORY FLAWED — RYAN HAD NO PHYSICAL INVOLVEMENT',
      subtitle: 'Unsubstantiated Accusation',
      narrative: [
        'You accused Ryan based on his threatening messages regarding server keys.',
        'Ryan sent hostile messages from his workstation, but building badge records verify he never left the office.',
      ],
      rebuttalPoints: [
        'Badge logs confirm Ryan remained on Floor 14.',
        'Ryan did not know the location or code for Locker 28.',
      ],
      scoreMultiplier: 0.4,
      rank: 'F',
    },
    wrong_suspect_daniel: {
      id: 'wrong_suspect_daniel',
      type: 'failed',
      title: 'THEORY FLAWED — DANIEL WAS A HIRED DRIVER',
      subtitle: 'Incorrect Culprit',
      narrative: [
        'You accused Daniel because of his rendezvous arrangement near Riverside Overlook.',
        'Daniel was merely a paid transport driver contracted by Sarah. He left the area when surveillance vehicles appeared.',
      ],
      scoreMultiplier: 0.4,
      rank: 'F',
    },
    incomplete_theory: {
      id: 'incomplete_theory',
      type: 'incomplete',
      title: 'INSUFFICIENT EVIDENCE',
      subtitle: 'Theory Lacks Supporting Evidence',
      narrative: [
        'Your report lacks the necessary evidence connections to establish what transpired at 3:17 AM.',
        'Review the evidence on the Investigation Board and reconstruct the missing deductions before filing.',
      ],
      scoreMultiplier: 0.2,
      rank: 'F',
    },
  },
};
